sonar.projectKey=Thomas-Boutin_CheatShqip
sonar.projectName=CheatShqip
sonar.host.url=https://sonarcloud.io
sonar.organization=thomas-boutin

sonar.sources=app/src/main/java,app/src/prod/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.java.binaries=app/build/tmp/kotlin-classes/prodDebug
sonar.java.test.binaries=app/build/tmp/kotlin-classes/prodDebugUnitTest
sonar.junit.reportsPath=app/build/test-results/testProdDebugUnitTest,app/build/test-results/testMockDebugUnitTest
sonar.android.lint.report=app/build/reports/lint-results-prodDebug.xml

sonar.exclusions=**/build/**
