sonar.projectKey=Thomas-Boutin_CheatShqip
sonar.projectName=CheatShqip
sonar.host.url=https://sonarcloud.io
sonar.organization=thomas-boutin

sonar.sources=app/src/main/java
sonar.tests=app/src/test/java,app/src/androidTest/java
sonar.java.binaries=app/build/tmp/kotlin-classes/debug
sonar.java.test.binaries=app/build/tmp/kotlin-classes/debugUnitTest
sonar.junit.reportsPath=app/build/test-results/testDebugUnitTest
sonar.android.lint.report=app/build/reports/lint-results-debug.xml

sonar.exclusions=**/build/**
